version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "development"
    schedule:
      interval: "daily"
      time: "02:00"
    labels:
      - "Action: no bump"
