name: Deployment

on: deployment

jobs:
  npm:
    name: 'Deploy on npm'
    runs-on: ubuntu-latest

    steps:
    - name: Update deployment status
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        previews: 'ant-man,flash'
        script: |
          const name = context.payload.deployment.payload.name;
          const version = context.payload.deployment.payload.version;
          const npmUrl = `https://www.npmjs.com/package/${name}/v/${version}`;

          const { data: deploymentStatus } = github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ github.event.deployment.id }}',
            environment_url: npmUrl,
            description: `Publishing ${name}@${version} on npm`,
            auto_inactive: false,
            state: 'in_progress',
          });

    - name: 'Download artifact'
      id: download-artifact
      uses: actions/github-script@v3.1.0
      with:
        script: |
          const download = await github.actions.downloadArtifact({
             owner: context.repo.owner,
             repo: context.repo.repo,
             artifact_id: context.payload.deployment.payload.artifact_id,
             archive_format: 'zip',
          });

          const fs = require('fs');
          fs.writeFileSync('${{github.workspace}}/package.zip', Buffer.from(download.data));

    - name: 'Unzip artifact'
      run: |
        unzip package.zip
        tar -xvf package.tgz

    - uses: actions/setup-node@v2
      with:
        registry-url: https://registry.npmjs.org/
        node-version: '14'

    - name: Publish npm
      id: publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_NPM }}
      run: |
        npm publish package.tgz --access public --tag ${{ github.event.deployment.payload.npmTag }}

        echo "::set-output name=state::done"

    - name: Update deployment status
      if: always()
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        previews: 'ant-man,flash'
        script: |
          const name = context.payload.deployment.payload.name;
          const version = context.payload.deployment.payload.version;
          const npmUrl = `https://www.npmjs.com/package/${name}/v/${version}`;

          const state = '${{ steps.publish.outputs.state }}' === 'done' ? 'success' : 'failure';

          const { data: deploymentStatus } = github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ github.event.deployment.id }}',
            environment_url: npmUrl,
            description: `Published ${name}@${version} on npm`,
            auto_inactive: false,
            state,
          });
