name: Pull request

on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, reopened, synchronize, ready_for_review]

jobs:
  assignee:
    name: 'check assignee'
    runs-on: ubuntu-18.04

    env:
      ASSIGNEES: ${{ toJson(github.event.pull_request.assignees) }}

    steps:
    - name: Fail if no assignee
      run: |
        LENGTH=$(echo $ASSIGNEES | jq 'length')

        if [[ "$LENGTH" -le "0" ]]; then
          echo "::error ::Missing assignee on PR"
          exit 1
        fi

  version-labels:
    name: 'check version label'
    runs-on: ubuntu-18.04

    steps:
    - name: Check if version label is present
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const versionLabels = [
            'no-release',
            'patch',
            'minor',
            'major',
          ];

          const { data: labels } = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            per_page: 100,
          });

          const versionLabelsPresent = labels
            .filter(label => versionLabels.includes(label.name))

          if (versionLabelsPresent.length === 1) {
            return;
          }

          console.log(`::debug ::${versionLabelsPresent.length} matching labels`);

          throw new Error('Should have one and only one of no-release, patch, minor, major labels');
