name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: 'Create Release'
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - name: Extract release changelog
      id: extract-changelog
      run: |
        VERSION=$(cat package.json | jq -r '.version')
        VERSION_PART=$(sed -n "/## \[$VERSION\]/,/## \[/{/## \[/d;p;}" CHANGELOG.md)

        echo VERSION_PART=$VERSION_PART

        echo "::set-output name=version::$VERSION"
        echo "::set-output name=version-part::$VERSION_PART"

    - name: Create Release
      uses: actions/github-script@0.4.0
      env:
        COMMIT: ${{ github.sha }}
        VERSION: ${{ steps.extract-changelog.outputs.version }}
        BODY: ${{ steps.extract-changelog.outputs.version-part }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${process.env.VERSION}`,
            target_commitish: process.env.COMMIT,
            name: process.env.TAG,
            body: process.env.BODY,
            draft: false,
            prerelease: false,
          })
